### ISSUE TITLE
Cursor color when positioning on braces, brackets and brackets

### ISSUE THREAD

**Issue by terroo** [Matsuuu/pinkmare#1]
Dude, excellent this theme! I installed it here and found it perfect. There is only one thing that I did not adapt, it is the color of the cursor when selecting braces, brackets, equal parentheses. How can I change just that?

![suggestion](https://user-images.githubusercontent.com/41500739/109965869-510f5a80-7cce-11eb-8922-a5ebf4d49738.jpg)

**Comment by Matsuuu** [comment]
Cheers mate,

So let me see if I understood right: 

You would want to modify the color of the cursor turns when matching brackets when hovering over them, right?

So you want to make it a custom color, or just some other color?

**Comment by Matsuuu** [comment]
The color of the cursor is always automatic according to the underlying character of the cursor.

To change the pairing cursor, you need to configure your MatchParen settings

e.g.
```
hi! MatchParen cterm=NONE,bold gui=NONE,bold guibg=#87c095 guifg=NONE
```

I'll add the pinkmare color codes to the readme soon

**Comment by terroo** [comment]
Yes, cursor hover brackets . I used this line of code, but it didn't work

**Comment by terroo** [comment]
I changed it to the color I want and now it worked perfectly! Thank you very much!
