### ISSUE TITLE
Color of opening bracket is invisible when the cursor is one it

### ISSUE THREAD

**Issue by zeddo123** [Matsuuu/pinkmare#2]
When the cursor is on the left bracket, the cursor seems as if it's on the closing bracket, which is quite confusing, because the color of the cursor is "invisible" .

### How to reproduce
Go over an opening bracket and you will see that the cursor is on it but the closing bracket is the one highlighted.

**Comment by Matsuuu** [comment]
This feels more like a MatchParen problem than a theme problem.

Could you try 

```
hi! MatchParen cterm=NONE,bold gui=NONE,bold guibg=#87c095 guifg=NONE
```

And report back?

**Comment by zeddo123** [comment]
>Could you try
  hi! MatchParen cterm=NONE,bold gui=NONE,bold guibg=#87c095 guifg=NONE

Yeah this line seems to have fixed it for me.
Thank you :smile:
