### ISSUE TITLE
Weird black colors. 

### ISSUE THREAD

**Issue by FelipPalermo** [Matsuuu/pinkmare#4]
This error is not new for me, but when I have it on windows I just change the "enable_guicolors" for true and it works, but I have no clue how to fix that on macOS.  

on/off enable_guicolors. https://imgur.com/a/pxJu8yV.

**Comment by soveckyFonarik** [comment]
Good afternoon
does this theme support vim?
error on line 18 "let g:colors_name = 'pinkmare'"
maybe I'm doing something wrong?

**Comment by Matsuuu** [comment]
Do read the README :)

https://github.com/Matsuuu/pinkmare?tab=readme-ov-file#usage

```
set termguicolors
colorscheme pinkmare
```
