### ISSUE TITLE
Broken colors in neovim 0.10

### ISSUE THREAD

**Issue by niveK77pur** [Matsuuu/pinkmare#7]
# Issue

Heya, since the 0.10 release of neovim I notice some of the colors are off. As a matter of fact, this new version has changed the defaults of some highlight groups (quoted from [release notes](https://neovim.io/doc/user/news-0.10.html)):

> - These Nvim specific highlight groups are now defined in a meaningfully different way and might need an update:
>   - hl-FloatBorder is linked to hl-NormalFloat instead of hl-WinSeparator.
>   - hl-NormalFloat is not linked to hl-Pmenu.
>   - hl-WinBar has different background.
>   - hl-WinBarNC is similar to hl-WinBar but not bold.
>   - hl-WinSeparator is linked to hl-Normal instead of hl-VertSplit.
> - This also might result into some color schemes looking differently due to them relying on implicit assumptions about how highlight groups are defined by default. To account for this, define all attributes of highlight groups explicitly. Alternatively, use :colorscheme vim or :source $VIMRUNTIME/colors/vim.lua to restore previous definitions. 

This is likely at the source of the issue, and the solution is to explicitly define these highlight groups, as mentioned in the last bullet point.

# Screenshots

For the sake of reference, here some screenshots comparing neovim 0.10.0 and 0.9.5; there are probably a few more cases where the colors are off.

## Lazy.nvim

v0.10.0
![image](https://github.com/Matsuuu/pinkmare/assets/10981161/a40f33a4-9e9d-4f9e-8fc3-1d3cd31cd316)

v0.9.5
![image](https://github.com/Matsuuu/pinkmare/assets/10981161/e2466dd4-732d-4cc4-9662-4bb5110c288d)

## Diagnostics

v0.10.0
![image](https://github.com/Matsuuu/pinkmare/assets/10981161/56cb8fbc-290d-47c3-a705-9f8c0a1f0efa)
v0.9.5
![image](https://github.com/Matsuuu/pinkmare/assets/10981161/9ed219d7-69b2-4516-8e48-1e967653e1b4)

## Completion menu

v0.10.0
![image](https://github.com/Matsuuu/pinkmare/assets/10981161/59054bd8-b500-4867-99a9-550db4d5dd53)
v0.9.5
![image](https://github.com/Matsuuu/pinkmare/assets/10981161/351e5de1-ee6f-4037-89e9-28b8dd96cdf1)

**Comment by Matsuuu** [comment]
Thank you so much for reporting this! I've not been able to update to 0.10 yet so I've not run into these problems yet. I'll try and find some time to take a look at these in the near future

**Comment by Matsuuu** [comment]
@niveK77pur I've pushed some changes that should fix the background issues. I'm looking into the others currently (like the new inline hint colors). If you have any tips on what HL keywords I should target, do tell. Thanks!

**Comment by niveK77pur** [comment]
Thanks a lot for the update! It might be a while before I can look into it myself unfortunately, but if I do find something I will be sure to drop another comment here!

**Comment by Matsuuu** [comment]
As there seems to be no more reports on this, I'm closing this issue for now
